# Generated by Django 3.0.8 on 2020-07-18 14:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
                ('email', models.EmailField(max_length=255, verbose_name='Eメール')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('picture', models.ImageField(upload_to='images/')),
            ],
            options={
                'db_table': 'owner',
            },
        ),
    ]
