# Generated by Django 3.0.8 on 2020-07-19 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner', '0002_auto_20200719_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='name',
            new_name='username',
        ),
    ]
